# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='canino',
            options={'managed': True},
        ),
    ]
