# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioquimica',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='canino',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examen_fisico',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hemograma',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='informacion_clinica',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='informacion_habitacional',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='informacion_personal',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='informacion_regional',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
