# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-27 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0002_auto_20160327_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canino',
            name='fecha',
        ),
    ]
