# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0002_auto_20160209_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('clave', models.CharField(max_length=20)),
                ('clave_conf', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='propietario',
            name='datos_personales',
        ),
        migrations.AddField(
            model_name='propietario',
            name='barrio',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='numero_convivientes_adultos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='numero_convivientes_ninios',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='telefono',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Informacion_personal',
        ),
    ]
