# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-16 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0003_auto_20160815_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analisis',
            old_name='prifesional',
            new_name='profesional',
        ),
    ]
