# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0003_remove_canino_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='ultima_inundacion',
            field=models.DateField(),
        ),
    ]
