# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0004_auto_20160504_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
