# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0005_propietario_signos_clinicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vete.Propietario'),
        ),
    ]
