# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-05 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0006_auto_20160505_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='T',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='ChCM',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='GB',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='GR',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='HCM',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='Hb',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='VCM',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hemograma',
            name='s_o_l',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
