# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-08 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0007_auto_20160505_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='mascotas',
            field=models.CharField(max_length=100),
        ),
    ]
