# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-13 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0009_auto_20160925_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='raza',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
