# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0010_auto_20161113_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='edad',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='canino',
            name='raza',
            field=models.CharField(max_length=40),
        ),
    ]
