# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0011_auto_20161114_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='T',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='canino',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
