# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-16 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vete', '0013_auto_20161114_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canino',
            name='edad',
            field=models.FloatField(),
        ),
    ]
